CREATE TABLE BOOKS {
    ID INT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR_ID INT FOREIGN KEY REFERENCES AUTHORS(ID),
    ISBN INT NOT NULL,
    COPIES_OWNED INT NOT NULL,
    COPIES_AVAILABLE INT NOT NULL
    }

CREATE TABLE USERS {
    ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    AUTHOR_ID INT FOREIGN KEY REFERENCES AUTHORS(ID)
    }

CREATE TABLE AUTHORS {
    ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL
    }

CREATE TABLE BORROWED_BOOKS {
    ID INT PRIMARY KEY,
    BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID),
    OWNER_ID INT FOREIGN KEY REFERENCES USERS(ID),
    DUE_DATE DATE NOT NULL
    }

insert into authors(FIRST_NAME, LAST_NAME)
values
('Simona', 'Popescu'),
('Claudiu', 'Komartin'),
('Lavinia', 'Braniște'),
('Mariana', 'Marin');